all:
  children:
    masters:
      hosts:
        master1: 
          ansible_host: 34.220.197.170
    workers:
      hosts:
        worker1:
          ansible_host: 18.236.105.146
        worker2:
          ansible_host: 18.236.163.252
  vars:
    ansible_connection: ssh 
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ./key.pem
