all:
  children:
    masters:
      hosts:
        master1: 
          ansible_host: 10.0.3.117
    workers:
      hosts:
        worker1:
          ansible_host: 10.0.3.232
        worker2:
          ansible_host: 10.0.4.212
  vars:
    ansible_connection: ssh 
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ./key.pem
